spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  cache:
    type: redis
    redis:
      time-to-live: 30m
      cache-null-values: true
  data:
    redis:
      host: localhost
      port: 6379
      password: password

server:
  port: 8050